FROM maven:3.8-openjdk-17 as builder
WORKDIR /app
COPY pom.xml
RUN mvn dependency-go-offline
COPY src ./src
RUN mvn package

# using java to run the application
FROM ibm-semeru-runtimes:open-17-jre-centos7
WORKDIR /app
COPY --from=builder /app/target/chatty-*.jar
chatty.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","chatty.jar"]